---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pingone.io
  resources:
  - pingaccesses
  - pingauthorizepaps
  - pingauthorizes
  - pingdataconsoles
  - pingdatasyncs
  - pingdirectories
  - pingdirectoryproxies
  - pingenvironments
  - pingfederates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pingone.io
  resources:
  - pingaccesses/finalizers
  - pingauthorizepaps/finalizers
  - pingauthorizes/finalizers
  - pingdataconsoles/finalizers
  - pingdatasyncs/finalizers
  - pingdirectories/finalizers
  - pingdirectoryproxies/finalizers
  - pingenvironments/finalizers
  - pingfederates/finalizers
  verbs:
  - update
- apiGroups:
  - pingone.io
  resources:
  - pingaccesses/status
  - pingauthorizepaps/status
  - pingauthorizes/status
  - pingdataconsoles/status
  - pingdatasyncs/status
  - pingdirectories/status
  - pingdirectoryproxies/status
  - pingenvironments/status
  - pingfederates/status
  verbs:
  - get
  - patch
  - update
