apiVersion: pingone.io/v1alpha1
kind: PingEnvironment
metadata:
  name: env-dev
  namespace: ping-environments
spec:
  tenantId: dev
  tier: development
  domain: dev.example.com
  ingress:
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
