//go:build !ignore_autogenerated

/*
Copyright 2024 Darkedges.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerSpec) DeepCopyInto(out *ContainerSpec) {
	*out = *in
	if in.WaitFor != nil {
		in, out := &in.WaitFor, &out.WaitFor
		*out = make([]WaitForSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerSpec.
func (in *ContainerSpec) DeepCopy() *ContainerSpec {
	if in == nil {
		return nil
	}
	out := new(ContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingAccessConfig) DeepCopyInto(out *PingAccessConfig) {
	*out = *in
	if in.ServerProfile != nil {
		in, out := &in.ServerProfile, &out.ServerProfile
		*out = new(ServerProfileSpec)
		**out = **in
	}
	if in.ServerProfileLayers != nil {
		in, out := &in.ServerProfileLayers, &out.ServerProfileLayers
		*out = make([]ServerProfileLayerSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingAccessConfig.
func (in *PingAccessConfig) DeepCopy() *PingAccessConfig {
	if in == nil {
		return nil
	}
	out := new(PingAccessConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingAccessSpec) DeepCopyInto(out *PingAccessSpec) {
	*out = *in
	in.AdminIngress.DeepCopyInto(&out.AdminIngress)
	in.EngineIngress.DeepCopyInto(&out.EngineIngress)
	in.Container.DeepCopyInto(&out.Container)
	in.Config.DeepCopyInto(&out.Config)
	in.ValuesOverride.DeepCopyInto(&out.ValuesOverride)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingAccessSpec.
func (in *PingAccessSpec) DeepCopy() *PingAccessSpec {
	if in == nil {
		return nil
	}
	out := new(PingAccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingAuthorizeConfig) DeepCopyInto(out *PingAuthorizeConfig) {
	*out = *in
	if in.ServerProfile != nil {
		in, out := &in.ServerProfile, &out.ServerProfile
		*out = new(ServerProfileSpec)
		**out = **in
	}
	if in.ServerProfileLayers != nil {
		in, out := &in.ServerProfileLayers, &out.ServerProfileLayers
		*out = make([]ServerProfileLayerSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingAuthorizeConfig.
func (in *PingAuthorizeConfig) DeepCopy() *PingAuthorizeConfig {
	if in == nil {
		return nil
	}
	out := new(PingAuthorizeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingAuthorizePAPConfig) DeepCopyInto(out *PingAuthorizePAPConfig) {
	*out = *in
	if in.ServerProfile != nil {
		in, out := &in.ServerProfile, &out.ServerProfile
		*out = new(ServerProfileSpec)
		**out = **in
	}
	if in.ServerProfileLayers != nil {
		in, out := &in.ServerProfileLayers, &out.ServerProfileLayers
		*out = make([]ServerProfileLayerSpec, len(*in))
		copy(*out, *in)
	}
	if in.EnableAPIHTTPCache != nil {
		in, out := &in.EnableAPIHTTPCache, &out.EnableAPIHTTPCache
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingAuthorizePAPConfig.
func (in *PingAuthorizePAPConfig) DeepCopy() *PingAuthorizePAPConfig {
	if in == nil {
		return nil
	}
	out := new(PingAuthorizePAPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingAuthorizePAPSpec) DeepCopyInto(out *PingAuthorizePAPSpec) {
	*out = *in
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.Container.DeepCopyInto(&out.Container)
	in.Config.DeepCopyInto(&out.Config)
	in.ValuesOverride.DeepCopyInto(&out.ValuesOverride)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingAuthorizePAPSpec.
func (in *PingAuthorizePAPSpec) DeepCopy() *PingAuthorizePAPSpec {
	if in == nil {
		return nil
	}
	out := new(PingAuthorizePAPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingAuthorizeSpec) DeepCopyInto(out *PingAuthorizeSpec) {
	*out = *in
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.Container.DeepCopyInto(&out.Container)
	in.Config.DeepCopyInto(&out.Config)
	in.ValuesOverride.DeepCopyInto(&out.ValuesOverride)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingAuthorizeSpec.
func (in *PingAuthorizeSpec) DeepCopy() *PingAuthorizeSpec {
	if in == nil {
		return nil
	}
	out := new(PingAuthorizeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerProfileLayerSpec) DeepCopyInto(out *ServerProfileLayerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerProfileLayerSpec.
func (in *ServerProfileLayerSpec) DeepCopy() *ServerProfileLayerSpec {
	if in == nil {
		return nil
	}
	out := new(ServerProfileLayerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerProfileSpec) DeepCopyInto(out *ServerProfileSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerProfileSpec.
func (in *ServerProfileSpec) DeepCopy() *ServerProfileSpec {
	if in == nil {
		return nil
	}
	out := new(ServerProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaitForSpec) DeepCopyInto(out *WaitForSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaitForSpec.
func (in *WaitForSpec) DeepCopy() *WaitForSpec {
	if in == nil {
		return nil
	}
	out := new(WaitForSpec)
	in.DeepCopyInto(out)
	return out
}
