//go:build !ignore_autogenerated

/*
Copyright 2024 Darkedges.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerSpec) DeepCopyInto(out *ContainerSpec) {
	*out = *in
	if in.WaitFor != nil {
		in, out := &in.WaitFor, &out.WaitFor
		*out = make([]WaitForSpec, len(*in))
		copy(*out, *in)
	}
	if in.IncludeVolumes != nil {
		in, out := &in.IncludeVolumes, &out.IncludeVolumes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirementsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerSecurityContext != nil {
		in, out := &in.ContainerSecurityContext, &out.ContainerSecurityContext
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerSpec.
func (in *ContainerSpec) DeepCopy() *ContainerSpec {
	if in == nil {
		return nil
	}
	out := new(ContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalIngressSpec) DeepCopyInto(out *GlobalIngressSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalIngressSpec.
func (in *GlobalIngressSpec) DeepCopy() *GlobalIngressSpec {
	if in == nil {
		return nil
	}
	out := new(GlobalIngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalServicesSpec) DeepCopyInto(out *GlobalServicesSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalServicesSpec.
func (in *GlobalServicesSpec) DeepCopy() *GlobalServicesSpec {
	if in == nil {
		return nil
	}
	out := new(GlobalServicesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressSpec) DeepCopyInto(out *IngressSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressSpec.
func (in *IngressSpec) DeepCopy() *IngressSpec {
	if in == nil {
		return nil
	}
	out := new(IngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingAccess) DeepCopyInto(out *PingAccess) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingAccess.
func (in *PingAccess) DeepCopy() *PingAccess {
	if in == nil {
		return nil
	}
	out := new(PingAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PingAccess) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingAccessConfig) DeepCopyInto(out *PingAccessConfig) {
	*out = *in
	if in.ServerProfile != nil {
		in, out := &in.ServerProfile, &out.ServerProfile
		*out = new(ServerProfileSpec)
		**out = **in
	}
	if in.ServerProfileLayers != nil {
		in, out := &in.ServerProfileLayers, &out.ServerProfileLayers
		*out = make([]ServerProfileLayerSpec, len(*in))
		copy(*out, *in)
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingAccessConfig.
func (in *PingAccessConfig) DeepCopy() *PingAccessConfig {
	if in == nil {
		return nil
	}
	out := new(PingAccessConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingAccessList) DeepCopyInto(out *PingAccessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PingAccess, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingAccessList.
func (in *PingAccessList) DeepCopy() *PingAccessList {
	if in == nil {
		return nil
	}
	out := new(PingAccessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PingAccessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingAccessSpec) DeepCopyInto(out *PingAccessSpec) {
	*out = *in
	in.AdminIngress.DeepCopyInto(&out.AdminIngress)
	in.EngineIngress.DeepCopyInto(&out.EngineIngress)
	in.Service.DeepCopyInto(&out.Service)
	in.Container.DeepCopyInto(&out.Container)
	in.Config.DeepCopyInto(&out.Config)
	in.ValuesOverride.DeepCopyInto(&out.ValuesOverride)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingAccessSpec.
func (in *PingAccessSpec) DeepCopy() *PingAccessSpec {
	if in == nil {
		return nil
	}
	out := new(PingAccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingAccessStatus) DeepCopyInto(out *PingAccessStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingAccessStatus.
func (in *PingAccessStatus) DeepCopy() *PingAccessStatus {
	if in == nil {
		return nil
	}
	out := new(PingAccessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingAuthorize) DeepCopyInto(out *PingAuthorize) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingAuthorize.
func (in *PingAuthorize) DeepCopy() *PingAuthorize {
	if in == nil {
		return nil
	}
	out := new(PingAuthorize)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PingAuthorize) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingAuthorizeConfig) DeepCopyInto(out *PingAuthorizeConfig) {
	*out = *in
	if in.ServerProfile != nil {
		in, out := &in.ServerProfile, &out.ServerProfile
		*out = new(ServerProfileSpec)
		**out = **in
	}
	if in.ServerProfileLayers != nil {
		in, out := &in.ServerProfileLayers, &out.ServerProfileLayers
		*out = make([]ServerProfileLayerSpec, len(*in))
		copy(*out, *in)
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingAuthorizeConfig.
func (in *PingAuthorizeConfig) DeepCopy() *PingAuthorizeConfig {
	if in == nil {
		return nil
	}
	out := new(PingAuthorizeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingAuthorizeList) DeepCopyInto(out *PingAuthorizeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PingAuthorize, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingAuthorizeList.
func (in *PingAuthorizeList) DeepCopy() *PingAuthorizeList {
	if in == nil {
		return nil
	}
	out := new(PingAuthorizeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PingAuthorizeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingAuthorizePAP) DeepCopyInto(out *PingAuthorizePAP) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingAuthorizePAP.
func (in *PingAuthorizePAP) DeepCopy() *PingAuthorizePAP {
	if in == nil {
		return nil
	}
	out := new(PingAuthorizePAP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PingAuthorizePAP) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingAuthorizePAPConfig) DeepCopyInto(out *PingAuthorizePAPConfig) {
	*out = *in
	if in.ServerProfile != nil {
		in, out := &in.ServerProfile, &out.ServerProfile
		*out = new(ServerProfileSpec)
		**out = **in
	}
	if in.ServerProfileLayers != nil {
		in, out := &in.ServerProfileLayers, &out.ServerProfileLayers
		*out = make([]ServerProfileLayerSpec, len(*in))
		copy(*out, *in)
	}
	if in.EnableAPIHTTPCache != nil {
		in, out := &in.EnableAPIHTTPCache, &out.EnableAPIHTTPCache
		*out = new(bool)
		**out = **in
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingAuthorizePAPConfig.
func (in *PingAuthorizePAPConfig) DeepCopy() *PingAuthorizePAPConfig {
	if in == nil {
		return nil
	}
	out := new(PingAuthorizePAPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingAuthorizePAPList) DeepCopyInto(out *PingAuthorizePAPList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PingAuthorizePAP, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingAuthorizePAPList.
func (in *PingAuthorizePAPList) DeepCopy() *PingAuthorizePAPList {
	if in == nil {
		return nil
	}
	out := new(PingAuthorizePAPList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PingAuthorizePAPList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingAuthorizePAPSpec) DeepCopyInto(out *PingAuthorizePAPSpec) {
	*out = *in
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.Service.DeepCopyInto(&out.Service)
	in.Container.DeepCopyInto(&out.Container)
	in.Config.DeepCopyInto(&out.Config)
	in.ValuesOverride.DeepCopyInto(&out.ValuesOverride)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingAuthorizePAPSpec.
func (in *PingAuthorizePAPSpec) DeepCopy() *PingAuthorizePAPSpec {
	if in == nil {
		return nil
	}
	out := new(PingAuthorizePAPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingAuthorizePAPStatus) DeepCopyInto(out *PingAuthorizePAPStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingAuthorizePAPStatus.
func (in *PingAuthorizePAPStatus) DeepCopy() *PingAuthorizePAPStatus {
	if in == nil {
		return nil
	}
	out := new(PingAuthorizePAPStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingAuthorizeSpec) DeepCopyInto(out *PingAuthorizeSpec) {
	*out = *in
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.Service.DeepCopyInto(&out.Service)
	in.Container.DeepCopyInto(&out.Container)
	in.Config.DeepCopyInto(&out.Config)
	in.ValuesOverride.DeepCopyInto(&out.ValuesOverride)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingAuthorizeSpec.
func (in *PingAuthorizeSpec) DeepCopy() *PingAuthorizeSpec {
	if in == nil {
		return nil
	}
	out := new(PingAuthorizeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingAuthorizeStatus) DeepCopyInto(out *PingAuthorizeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingAuthorizeStatus.
func (in *PingAuthorizeStatus) DeepCopy() *PingAuthorizeStatus {
	if in == nil {
		return nil
	}
	out := new(PingAuthorizeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingDataConsole) DeepCopyInto(out *PingDataConsole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingDataConsole.
func (in *PingDataConsole) DeepCopy() *PingDataConsole {
	if in == nil {
		return nil
	}
	out := new(PingDataConsole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PingDataConsole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingDataConsoleConfig) DeepCopyInto(out *PingDataConsoleConfig) {
	*out = *in
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingDataConsoleConfig.
func (in *PingDataConsoleConfig) DeepCopy() *PingDataConsoleConfig {
	if in == nil {
		return nil
	}
	out := new(PingDataConsoleConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingDataConsoleInlineSpec) DeepCopyInto(out *PingDataConsoleInlineSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	in.Ingress.DeepCopyInto(&out.Ingress)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingDataConsoleInlineSpec.
func (in *PingDataConsoleInlineSpec) DeepCopy() *PingDataConsoleInlineSpec {
	if in == nil {
		return nil
	}
	out := new(PingDataConsoleInlineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingDataConsoleList) DeepCopyInto(out *PingDataConsoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PingDataConsole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingDataConsoleList.
func (in *PingDataConsoleList) DeepCopy() *PingDataConsoleList {
	if in == nil {
		return nil
	}
	out := new(PingDataConsoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PingDataConsoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingDataConsoleSpec) DeepCopyInto(out *PingDataConsoleSpec) {
	*out = *in
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.Service.DeepCopyInto(&out.Service)
	in.Container.DeepCopyInto(&out.Container)
	in.Config.DeepCopyInto(&out.Config)
	in.ValuesOverride.DeepCopyInto(&out.ValuesOverride)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingDataConsoleSpec.
func (in *PingDataConsoleSpec) DeepCopy() *PingDataConsoleSpec {
	if in == nil {
		return nil
	}
	out := new(PingDataConsoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingDataConsoleStatus) DeepCopyInto(out *PingDataConsoleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingDataConsoleStatus.
func (in *PingDataConsoleStatus) DeepCopy() *PingDataConsoleStatus {
	if in == nil {
		return nil
	}
	out := new(PingDataConsoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingDataSync) DeepCopyInto(out *PingDataSync) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingDataSync.
func (in *PingDataSync) DeepCopy() *PingDataSync {
	if in == nil {
		return nil
	}
	out := new(PingDataSync)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PingDataSync) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingDataSyncConfig) DeepCopyInto(out *PingDataSyncConfig) {
	*out = *in
	if in.ServerProfile != nil {
		in, out := &in.ServerProfile, &out.ServerProfile
		*out = new(ServerProfileSpec)
		**out = **in
	}
	if in.ServerProfileLayers != nil {
		in, out := &in.ServerProfileLayers, &out.ServerProfileLayers
		*out = make([]ServerProfileLayerSpec, len(*in))
		copy(*out, *in)
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingDataSyncConfig.
func (in *PingDataSyncConfig) DeepCopy() *PingDataSyncConfig {
	if in == nil {
		return nil
	}
	out := new(PingDataSyncConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingDataSyncList) DeepCopyInto(out *PingDataSyncList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PingDataSync, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingDataSyncList.
func (in *PingDataSyncList) DeepCopy() *PingDataSyncList {
	if in == nil {
		return nil
	}
	out := new(PingDataSyncList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PingDataSyncList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingDataSyncSpec) DeepCopyInto(out *PingDataSyncSpec) {
	*out = *in
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.Service.DeepCopyInto(&out.Service)
	in.Container.DeepCopyInto(&out.Container)
	in.Config.DeepCopyInto(&out.Config)
	in.ValuesOverride.DeepCopyInto(&out.ValuesOverride)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingDataSyncSpec.
func (in *PingDataSyncSpec) DeepCopy() *PingDataSyncSpec {
	if in == nil {
		return nil
	}
	out := new(PingDataSyncSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingDataSyncStatus) DeepCopyInto(out *PingDataSyncStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingDataSyncStatus.
func (in *PingDataSyncStatus) DeepCopy() *PingDataSyncStatus {
	if in == nil {
		return nil
	}
	out := new(PingDataSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingDirectory) DeepCopyInto(out *PingDirectory) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingDirectory.
func (in *PingDirectory) DeepCopy() *PingDirectory {
	if in == nil {
		return nil
	}
	out := new(PingDirectory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PingDirectory) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingDirectoryConfig) DeepCopyInto(out *PingDirectoryConfig) {
	*out = *in
	if in.ServerProfile != nil {
		in, out := &in.ServerProfile, &out.ServerProfile
		*out = new(ServerProfileSpec)
		**out = **in
	}
	if in.ServerProfileLayers != nil {
		in, out := &in.ServerProfileLayers, &out.ServerProfileLayers
		*out = make([]ServerProfileLayerSpec, len(*in))
		copy(*out, *in)
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingDirectoryConfig.
func (in *PingDirectoryConfig) DeepCopy() *PingDirectoryConfig {
	if in == nil {
		return nil
	}
	out := new(PingDirectoryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingDirectoryList) DeepCopyInto(out *PingDirectoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PingDirectory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingDirectoryList.
func (in *PingDirectoryList) DeepCopy() *PingDirectoryList {
	if in == nil {
		return nil
	}
	out := new(PingDirectoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PingDirectoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingDirectoryProxy) DeepCopyInto(out *PingDirectoryProxy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingDirectoryProxy.
func (in *PingDirectoryProxy) DeepCopy() *PingDirectoryProxy {
	if in == nil {
		return nil
	}
	out := new(PingDirectoryProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PingDirectoryProxy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingDirectoryProxyConfig) DeepCopyInto(out *PingDirectoryProxyConfig) {
	*out = *in
	if in.ServerProfile != nil {
		in, out := &in.ServerProfile, &out.ServerProfile
		*out = new(ServerProfileSpec)
		**out = **in
	}
	if in.ServerProfileLayers != nil {
		in, out := &in.ServerProfileLayers, &out.ServerProfileLayers
		*out = make([]ServerProfileLayerSpec, len(*in))
		copy(*out, *in)
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingDirectoryProxyConfig.
func (in *PingDirectoryProxyConfig) DeepCopy() *PingDirectoryProxyConfig {
	if in == nil {
		return nil
	}
	out := new(PingDirectoryProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingDirectoryProxyList) DeepCopyInto(out *PingDirectoryProxyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PingDirectoryProxy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingDirectoryProxyList.
func (in *PingDirectoryProxyList) DeepCopy() *PingDirectoryProxyList {
	if in == nil {
		return nil
	}
	out := new(PingDirectoryProxyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PingDirectoryProxyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingDirectoryProxySpec) DeepCopyInto(out *PingDirectoryProxySpec) {
	*out = *in
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.Service.DeepCopyInto(&out.Service)
	in.Container.DeepCopyInto(&out.Container)
	in.Config.DeepCopyInto(&out.Config)
	in.ValuesOverride.DeepCopyInto(&out.ValuesOverride)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingDirectoryProxySpec.
func (in *PingDirectoryProxySpec) DeepCopy() *PingDirectoryProxySpec {
	if in == nil {
		return nil
	}
	out := new(PingDirectoryProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingDirectoryProxyStatus) DeepCopyInto(out *PingDirectoryProxyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingDirectoryProxyStatus.
func (in *PingDirectoryProxyStatus) DeepCopy() *PingDirectoryProxyStatus {
	if in == nil {
		return nil
	}
	out := new(PingDirectoryProxyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingDirectorySpec) DeepCopyInto(out *PingDirectorySpec) {
	*out = *in
	in.Service.DeepCopyInto(&out.Service)
	in.Container.DeepCopyInto(&out.Container)
	in.Config.DeepCopyInto(&out.Config)
	in.ValuesOverride.DeepCopyInto(&out.ValuesOverride)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingDirectorySpec.
func (in *PingDirectorySpec) DeepCopy() *PingDirectorySpec {
	if in == nil {
		return nil
	}
	out := new(PingDirectorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingDirectoryStatus) DeepCopyInto(out *PingDirectoryStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingDirectoryStatus.
func (in *PingDirectoryStatus) DeepCopy() *PingDirectoryStatus {
	if in == nil {
		return nil
	}
	out := new(PingDirectoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingEnvironment) DeepCopyInto(out *PingEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingEnvironment.
func (in *PingEnvironment) DeepCopy() *PingEnvironment {
	if in == nil {
		return nil
	}
	out := new(PingEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PingEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingEnvironmentList) DeepCopyInto(out *PingEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PingEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingEnvironmentList.
func (in *PingEnvironmentList) DeepCopy() *PingEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(PingEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PingEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingEnvironmentSpec) DeepCopyInto(out *PingEnvironmentSpec) {
	*out = *in
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.Services.DeepCopyInto(&out.Services)
	if in.PingDataConsole != nil {
		in, out := &in.PingDataConsole, &out.PingDataConsole
		*out = new(PingDataConsoleInlineSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Vault != nil {
		in, out := &in.Vault, &out.Vault
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerSecurityContext != nil {
		in, out := &in.ContainerSecurityContext, &out.ContainerSecurityContext
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirementsSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Volumes.DeepCopyInto(&out.Volumes)
	if in.IncludeVolumes != nil {
		in, out := &in.IncludeVolumes, &out.IncludeVolumes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingEnvironmentSpec.
func (in *PingEnvironmentSpec) DeepCopy() *PingEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(PingEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingEnvironmentStatus) DeepCopyInto(out *PingEnvironmentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingEnvironmentStatus.
func (in *PingEnvironmentStatus) DeepCopy() *PingEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(PingEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingFederate) DeepCopyInto(out *PingFederate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingFederate.
func (in *PingFederate) DeepCopy() *PingFederate {
	if in == nil {
		return nil
	}
	out := new(PingFederate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PingFederate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingFederateConfig) DeepCopyInto(out *PingFederateConfig) {
	*out = *in
	if in.ServerProfile != nil {
		in, out := &in.ServerProfile, &out.ServerProfile
		*out = new(ServerProfileSpec)
		**out = **in
	}
	if in.ServerProfileLayers != nil {
		in, out := &in.ServerProfileLayers, &out.ServerProfileLayers
		*out = make([]ServerProfileLayerSpec, len(*in))
		copy(*out, *in)
	}
	if in.EnableAutomaticHeapDump != nil {
		in, out := &in.EnableAutomaticHeapDump, &out.EnableAutomaticHeapDump
		*out = new(bool)
		**out = **in
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingFederateConfig.
func (in *PingFederateConfig) DeepCopy() *PingFederateConfig {
	if in == nil {
		return nil
	}
	out := new(PingFederateConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingFederateList) DeepCopyInto(out *PingFederateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PingFederate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingFederateList.
func (in *PingFederateList) DeepCopy() *PingFederateList {
	if in == nil {
		return nil
	}
	out := new(PingFederateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PingFederateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingFederateSpec) DeepCopyInto(out *PingFederateSpec) {
	*out = *in
	in.EngineIngress.DeepCopyInto(&out.EngineIngress)
	in.AdminIngress.DeepCopyInto(&out.AdminIngress)
	in.Service.DeepCopyInto(&out.Service)
	in.Container.DeepCopyInto(&out.Container)
	in.Config.DeepCopyInto(&out.Config)
	in.ValuesOverride.DeepCopyInto(&out.ValuesOverride)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingFederateSpec.
func (in *PingFederateSpec) DeepCopy() *PingFederateSpec {
	if in == nil {
		return nil
	}
	out := new(PingFederateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingFederateStatus) DeepCopyInto(out *PingFederateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingFederateStatus.
func (in *PingFederateStatus) DeepCopy() *PingFederateStatus {
	if in == nil {
		return nil
	}
	out := new(PingFederateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequirementsSpec) DeepCopyInto(out *ResourceRequirementsSpec) {
	*out = *in
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequirementsSpec.
func (in *ResourceRequirementsSpec) DeepCopy() *ResourceRequirementsSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceRequirementsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerProfileLayerSpec) DeepCopyInto(out *ServerProfileLayerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerProfileLayerSpec.
func (in *ServerProfileLayerSpec) DeepCopy() *ServerProfileLayerSpec {
	if in == nil {
		return nil
	}
	out := new(ServerProfileLayerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerProfileSpec) DeepCopyInto(out *ServerProfileSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerProfileSpec.
func (in *ServerProfileSpec) DeepCopy() *ServerProfileSpec {
	if in == nil {
		return nil
	}
	out := new(ServerProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpec.
func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaitForSpec) DeepCopyInto(out *WaitForSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaitForSpec.
func (in *WaitForSpec) DeepCopy() *WaitForSpec {
	if in == nil {
		return nil
	}
	out := new(WaitForSpec)
	in.DeepCopyInto(out)
	return out
}
