// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *GlobalIngressSpec) DeepCopyInto(out *GlobalIngressSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy creates a deep copy of GlobalIngressSpec.
func (in *GlobalIngressSpec) DeepCopy() *GlobalIngressSpec {
	if in == nil {
		return nil
	}
	out := new(GlobalIngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *IngressSpec) DeepCopyInto(out *IngressSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy creates a deep copy of IngressSpec.
func (in *IngressSpec) DeepCopy() *IngressSpec {
	if in == nil {
		return nil
	}
	out := new(IngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *PingFederateConfig) DeepCopyInto(out *PingFederateConfig) {
	*out = *in
}

// DeepCopy creates a deep copy of PingFederateConfig.
func (in *PingFederateConfig) DeepCopy() *PingFederateConfig {
	if in == nil {
		return nil
	}
	out := new(PingFederateConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *PingDirectoryConfig) DeepCopyInto(out *PingDirectoryConfig) {
	*out = *in
}

// DeepCopy creates a deep copy of PingDirectoryConfig.
func (in *PingDirectoryConfig) DeepCopy() *PingDirectoryConfig {
	if in == nil {
		return nil
	}
	out := new(PingDirectoryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *PingEnvironment) DeepCopyInto(out *PingEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of PingEnvironment.
func (in *PingEnvironment) DeepCopy() *PingEnvironment {
	if in == nil {
		return nil
	}
	out := new(PingEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *PingEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *PingEnvironmentList) DeepCopyInto(out *PingEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PingEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of PingEnvironmentList.
func (in *PingEnvironmentList) DeepCopy() *PingEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(PingEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *PingEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *PingEnvironmentSpec) DeepCopyInto(out *PingEnvironmentSpec) {
	*out = *in
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.PingFederate.DeepCopyInto(&out.PingFederate)
	if in.PingDirectory != nil {
		in, out := &in.PingDirectory, &out.PingDirectory
		*out = new(PingDirectorySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy creates a deep copy of PingEnvironmentSpec.
func (in *PingEnvironmentSpec) DeepCopy() *PingEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(PingEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *PingEnvironmentStatus) DeepCopyInto(out *PingEnvironmentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of PingEnvironmentStatus.
func (in *PingEnvironmentStatus) DeepCopy() *PingEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(PingEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *PingFederateSpec) DeepCopyInto(out *PingFederateSpec) {
	*out = *in
	in.EngineIngress.DeepCopyInto(&out.EngineIngress)
	in.AdminIngress.DeepCopyInto(&out.AdminIngress)
	out.Config = in.Config
	in.ValuesOverride.DeepCopyInto(&out.ValuesOverride)
}

// DeepCopy creates a deep copy of PingFederateSpec.
func (in *PingFederateSpec) DeepCopy() *PingFederateSpec {
	if in == nil {
		return nil
	}
	out := new(PingFederateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *PingDataConsoleSpec) DeepCopyInto(out *PingDataConsoleSpec) {
	*out = *in
	in.Ingress.DeepCopyInto(&out.Ingress)
}

// DeepCopy creates a deep copy of PingDataConsoleSpec.
func (in *PingDataConsoleSpec) DeepCopy() *PingDataConsoleSpec {
	if in == nil {
		return nil
	}
	out := new(PingDataConsoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *PingDirectorySpec) DeepCopyInto(out *PingDirectorySpec) {
	*out = *in
	if in.Console != nil {
		in, out := &in.Console, &out.Console
		*out = new(PingDataConsoleSpec)
		(*in).DeepCopyInto(*out)
	}
	out.Config = in.Config
	in.ValuesOverride.DeepCopyInto(&out.ValuesOverride)
}

// DeepCopy creates a deep copy of PingDirectorySpec.
func (in *PingDirectorySpec) DeepCopy() *PingDirectorySpec {
	if in == nil {
		return nil
	}
	out := new(PingDirectorySpec)
	in.DeepCopyInto(out)
	return out
}
